### ISSUE TITLE
idea for another example

### ISSUE THREAD

**Issue by matackett** [mine-cetinkaya-rundel/take-a-chance#2]
How about redoing this graph as another example? 

Electric Skateboards Graph: https://www.electricskateboardhq.com/boards-comparison/
Data: https://compare-skateboards.com/#1488732069728-b989687a-f273

I can write up a short exercise.

**Comment by mine-cetinkaya-rundel** [comment]
Sounds good!


--

Mine Çetinkaya-Rundel
🔗 mine-cr.com
✍️ citizen-statistician.org
🐦 @minebocek
🔘 she/her
