### ISSUE TITLE
From drab to fab, what's left to do?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [mine-cetinkaya-rundel/take-a-chance#3]
- [x] Read over (@matackett can you read it over once?)
- [x] Add conclusion (@mine-cetinkaya-rundel will work on it in the morning)
- [x] Add other further reading?
- [x] Add code to repo as R scripts for the visualisations (cen be done after sending to editors)

**Comment by matackett** [comment]
This sounds good. I'll work on this in the morning. 

Do we have any restrictions such as word count to consider?

**Comment by mine-cetinkaya-rundel** [comment]
@matackett I don't think we need to worry about word count, however I was worried a bit about the number of figures / length (compared to previous columns) so I removed a couple steps and reduced the size of some of the figures. 

Adding R scripts to the repo doesn't need to hold up submission but let me know when you read it over and make further edits.

Also, do you think we have permission to include the electric skateboards image? I created the other "drab" figures so don't mind including but I wasn't sure about that one. I wonder if we should link to it. Maybe this is a question for Amanda?

**Comment by matackett** [comment]
@mine-cetinkaya-rundel Good point about the skateboard image; I'm not entirely sure how permissions work...
I recreated the drab skateboard plot, so maybe we can use that (?) and link to the original site.  If number of plots becomes a concern, we can also just remove the drab skateboard plot all together and  just have the link to the site.

I'm reading through the article now and will send final comments soon!

**Comment by matackett** [comment]
@mine-cetinkaya-rundel I read through it and made edits. I also added Healy's book to the list of references.

A few more things: 
- Can you add the title for the 2014 article in the first line? 
- In the list of resources, I couldn't get the link for Wikipedia to not run off of the page without adding some weird spacing...
- FYI: I had to comment out  `#theme: readable` to get it to knit, so the theme isn't applied in my updated version.

The article looks good! It gave me some ideas for when I teach 199 again 🙂

**Comment by mine-cetinkaya-rundel** [comment]
Alright, made the changes, and sending off!

**Comment by matackett** [comment]
I put the code for all of the improved visualizations in one R script. I can split them into separate scripts if this is too much for one file.

**Comment by mine-cetinkaya-rundel** [comment]
This works I think, thanks!
