### ISSUE TITLE
Examples of using covid-19 data in class?

### ISSUE THREAD

**Issue by matackett** [mine-cetinkaya-rundel/take-a-chance#4]
Are there any example assignments or class activities using covid-19 data?

**Comment by mine-cetinkaya-rundel** [comment]
I have a day one activity example that I used in some workshops, here is the link to it: https://rstudio.cloud/project/1444789

But it does require caution since it's about deaths.

**Comment by mine-cetinkaya-rundel** [comment]
There was also an assignment that got shared on isostat I think: https://rpruim.github.io/ds303/S20/hw/covid-19/covid-19.html

**Comment by mine-cetinkaya-rundel** [comment]
https://www.nytimes.com/2020/02/27/learning/dangerous-numbers-teaching-about-data-and-statistics-using-the-coronavirus-outbreak.html

**Comment by matackett** [comment]
Thanks! I'll use these to put together some example exercises and discussion questions.
