### ISSUE TITLE
datafest-covid: what's left

### ISSUE THREAD

**Issue by matackett** [mine-cetinkaya-rundel/take-a-chance#6]
- [x] Closing for DataFest section. Do we want to include anything about the winners or example projects? 
- [x] Add pictures or plots?
- [x] Maybe use a different title?
- [x] @mine-cetinkaya-rundel read through 
- [x] @matackett read through

**Comment by mine-cetinkaya-rundel** [comment]
Added some DF examples. Didn't add images, but could be convinced otherwise. See if you like especially the Duke ones.

Will read again tomorrow!

**Comment by mine-cetinkaya-rundel** [comment]
Ok, I didn't add any plots, but otherwise I think we're good. Just waiting on confirmation about footnotes.

Once you also read through @matackett we should be good to go!
